-- MySQL Script generated by MySQL Workbench
-- Thu Apr 10 22:23:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Battle_ship_user
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Battle_ship_user
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Battle_ship_user` DEFAULT CHARACTER SET utf8mb4 ;
USE `Battle_ship_user` ;

-- -----------------------------------------------------
-- Table `Battle_ship_user`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Battle_ship_user`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User_id` VARCHAR(45) NOT NULL,
  `Nick` VARCHAR(20) NOT NULL,
  `Login` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  `Win` INT NOT NULL,
  `Loss` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
